### ISSUE TITLE
Iniciar testes de rotas

### ISSUE THREAD

**Issue by DanilloGS** [fga-eps-mds/2019.2-Questmark#49]
# **Descrição**
Iniciar os testes nas rotas presentes no repositório 

# **Objetivos**
Iniciar o _TDD_ com o framework [Jest](https://jestjs.io/), afim de garantir a qualidade do código 

# Tasks
- [x]  Fazer  o teste do servidor e ser aprovado

- [x] Fazer o teste das rotas forms e ser aprovado

- [x] Fazer o teste do MongoDB e ser aprovado
