### ISSUE TITLE
Revisar documentos

### ISSUE THREAD

**Issue by DanilloGS** [fga-eps-mds/2019.2-Questmark#62]
# **Descrição**
Após o Feedback do professor Joenio e da professora Carla alguns documentos irão precisar de atenção especial.

# **Objetivo**
 Revisar e corrigir inconsistências no documento de arquitetura e no documento de visão. Instruir a equipe a escrever commits, pull request's e issues de uma forma mais consistente e esclarecedora e instruir, também, a escrever qualquer discussão pertinente a issue nos comentários da mesma.

 # **Tasks**
 - [x] Revisar e corrigir documento de visão; ( @DanilloGS )
 - [x] Revisar documento de arquitetura ( @lucaslop )
 - [x] Revisar toda a documentação e corrigir eventuais erros ortográficos; ( @Miguelisdemir e @lgpinheiro94 )
 - [x] Instruir equipe a utilizar a boas praticas no repositório. 
 ### **Documento de arquitetura**
 - [x] Adicionar diagrama de arquitetura ; ( @Gustavo-Nogueira , @lgpinheiro94 )
 - [x] Elaborar diagrama de pacotes; ( @DanilloGS )
 - [x] Corrigir as tecnologias utilizadas; ( @lucaslop )
 - [x] Adição de tópico: Padrão Arquitetural (MVC); ( @Gustavo-Nogueira )
 - [x] Tópico de visão de casos de uso; ( @Gustavo-Nogueira )
 - [x] Adicionar no documento as novas funcionalidades (CSV e iFrame); ( @DanilloGS  )
 - [x] Adicionar documentos que estiverem faltando. ( @lgpinheiro94 )

# **Comentários**
[Criando um bom Pull Request](https://academiadev.gitbook.io/joinville/pull-request/contribua.)
[Como escrever mensagens de commits no Git](https://www.lucascaton.com.br/2017/10/16/como-escrever-mensagens-de-commits-no-git/)

**Comment by DanilloGS** [comment]
Apesar de eu e o @nicaloribeiro termos sidos designados para essa issue os links são importantes para todos.
@lucaslop 
@Gustavo-Nogueira 
@Miguelisdemir 
@lgpinheiro94

**Comment by lucaslop** [comment]
A alteração dos documentos, vai ser feita no google drive ou no github? @DanilloGS

**Comment by DanilloGS** [comment]
@lucaslop vai ser feita na nossa branch docs mesmo

**Comment by lgpinheiro94** [comment]
Código de conduta será adicionado, seguindo o feedback recebido na release 1

**Comment by lgpinheiro94** [comment]
Foi criada uma nova branch para adição do código de conduta, 64-codigo_de_conduta

**Comment by Gustavo-Nogueira** [comment]
Primeira versão do diagrama de arquitetura:
![diagrama-v1](https://user-images.githubusercontent.com/36088551/66710083-cbd97d80-ed47-11e9-8dbc-28fcf91c321f.png)

**Comment by Gustavo-Nogueira** [comment]
## Referências para o desenvolvimento das tasks do documento de arquitetura:

https://fga-eps-mds.github.io/2019.2-FoodCare/produto/doc-arquitetura/

https://fga-eps-mds.github.io/2019.2-Acacia/#/architecture_document

https://fga-eps-mds.github.io/2019.2-Gymnasteg-Wiki/docs/docArquitetura

**Comment by DanilloGS** [comment]
Essa issue será adiada para a próxima sprint, pois existem mais arquivo faltantes que o esperado. O documento de visão será atualizado assim que conversarmos com a professora Carla sobre a nova proposta do projeto.

**Comment by DanilloGS** [comment]
Gente, faltam alguns documentos que não lembramos de fazer a escolha no sprint planning. Coloquem seus usuários do github na frente de um dos documentos faltantes.

**Comment by DanilloGS** [comment]
@lucaslop me dei a liberdade de atualizar um dos tópicos do documento de arquitetura. O documento ainda sim precisa de revisão e sua aprovação

**Comment by lucaslop** [comment]
Ok @DanilloGS

**Comment by lucaslop** [comment]
@DanilloGS Adicione as tecnologias faltantes e atualizei algumas informações no documento de arquitetura [5b9c742]

**Comment by Gustavo-Nogueira** [comment]
* Versão atualizada do diagrama de arquitetura.
![diagrama-v4](https://user-images.githubusercontent.com/36088551/68875102-059ffa00-06e1-11ea-873f-3dc227db8c26.png)

**Comment by DanilloGS** [comment]
O diagrama de pacotes está, atualmente, em produção.

**Comment by DanilloGS** [comment]
Adicionei os documentos e diagramas restantes. Além de ter corrigido os erros ortográficos que estavam presentes na wiki, finalizando assim o Epic.
